import FontFace from '@dmecke/game-engine/lib/Font/FontFace';
import Glyph from '@dmecke/game-engine/lib/Font/Glyph';

export default class MatchupPro12 implements FontFace {
    readonly image = 'fonts/matchup_pro_12_black.png';

    readonly height = 14;

    readonly glyphs = [
        [
            new Glyph(' ', 5),
            new Glyph('e', 6),
            new Glyph('d', 6),
            new Glyph('c', 5),
            new Glyph('b', 6),
            new Glyph('a', 6),
            new Glyph('`', 2),
            new Glyph('_', 4),
            new Glyph('^', 4),
            new Glyph(']', 4),
            new Glyph('f', 5),
            new Glyph('\\', 4),
            new Glyph('Z', 5),
            new Glyph('Y', 6),
            new Glyph('X', 6),
            new Glyph('W', 7),
            new Glyph('V', 7),
        ],
        [
            new Glyph('U', 6),
            new Glyph('T', 6),
            new Glyph('S', 5),
            new Glyph('R', 6),
            new Glyph('[', 4),
            new Glyph('Q', 6),
            new Glyph('g', 6),
            new Glyph('i', 4),
            new Glyph('}', 4),
            new Glyph('|', 2),
            new Glyph('{', 4),
            new Glyph('z', 5),
            new Glyph('y', 6),
            new Glyph('x', 6),
            new Glyph('w', 7),
            new Glyph('v', 6),
            new Glyph('u', 6),
        ],
        [
            new Glyph('h', 6),
            new Glyph('t', 4),
            new Glyph('r', 5),
            new Glyph('q', 6),
            new Glyph('p', 6),
            new Glyph('o', 6),
            new Glyph('n', 6),
            new Glyph('m', 7),
            new Glyph('l', 3),
            new Glyph('k', 6),
            new Glyph('j', 3),
            new Glyph('s', 5),
            new Glyph('P', 6),
            new Glyph('O', 6),
            new Glyph('N', 6),
            new Glyph('4', 5),
            new Glyph('3', 5),
        ],
        [
            new Glyph('2', 5),
            new Glyph('1', 5),
            new Glyph('0', 5),
            new Glyph('/', 4),
            new Glyph('.', 2),
            new Glyph('-', 4),
            new Glyph(',', 3),
            new Glyph('5', 5),
            new Glyph('+', 4),
            new Glyph(')', 4),
            new Glyph('(', 4),
            new Glyph('\'', 2),
            new Glyph('&', 6),
            new Glyph('%', 4),
            new Glyph('$', 6),
            new Glyph('#', 5),
            new Glyph('"', 4),
            new Glyph('!', 2),
            new Glyph('*', 5),
            new Glyph('6', 5),
        ],
        [
            new Glyph('7', 5),
            new Glyph('8', 5),
            new Glyph('M', 7),
            new Glyph('L', 5),
            new Glyph('K', 6),
            new Glyph('J', 3),
            new Glyph('I', 4),
            new Glyph('H', 6),
            new Glyph('G', 6),
            new Glyph('F', 5),
            new Glyph('E', 5),
            new Glyph('D', 6),
            new Glyph('C', 5),
            new Glyph('B', 6),
            new Glyph('A', 6),
            new Glyph('@', 12),
        ],
        [
            new Glyph('?', 4),
            new Glyph('>', 3),
            new Glyph('=', 4),
            new Glyph('<', 3),
            new Glyph(';', 3),
            new Glyph(':', 2),
            new Glyph('9', 5),
            new Glyph('~', 5),
        ],
    ];
}
