name: Continuous Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: install node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - name: install dependencies
              run: yarn install

            - name: build
              run: yarn run build

            - name: add metadata
              run: |
                  touch dist/meta
                  git log --format=%cd | tail -1 >> dist/meta
                  git log -1 --format=%cd >> dist/meta
                  grep -A 1 "@dmecke/game-engine@" yarn.lock | tail -1 | awk '{print $2}' | tr -d '"' >> dist/meta

            - name: deploy
              uses: easingthemes/ssh-deploy@v2
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  SOURCE: "dist/"
                  REMOTE_HOST: "server20.cunningsoft.de"
                  REMOTE_USER: "dmecke"
                  TARGET: "/var/www/html/cunningsoft.de/games/systemic-sandbox/"
